baseURL = "https://relaxed-banach-328df0.netlify.app/"
languageCode = "en-us"
title = "JAMSite"
copyright =  "(c) 2020 Marc Bakker"
theme="tale"
disableKinds = ["section"]
[params]
	customCSS = ["assets/css/custom_styles.css"]
[outputs]
	home = ["HTML", "JSON"]