baseURL = "https://reposman33.github.io/Udemy-JAMSite/"
languageCode = "en-us"
title = "JAMsite"
theme = "tale"
copyright =  "(c) 2020 Marc Bakker"
disableKinds = ["section"]
publishDir = "docs"
[params]
	customCSS = ["assets/sass/custom_styles.scss"]
[outputs]
	home = ["HTML", "JSON"]
